ci:
  autoupdate_schedule: quarterly
  skip:
    - ripsecrets
    - jsonschema2md-basic
    - jsonschema2md-food
    - jsonschema2md-ms2rescore
    - jsonschema2md-vegetables

repos:
  - repo: local
    hooks:
      - &jsonschema2md
        id: jsonschema2md-basic
        name: Generate the markdown documentation related to a JSON schema
        entry: jsonschema2md
        language: python
        files: examples/basic.json
        pass_filenames: false
        args:
          - --pre-commit
          - examples/basic.json
          - examples/basic.md
      - <<: *jsonschema2md
        id: jsonschema2md-food
        files: examples/food.json
        args:
          - --pre-commit
          - examples/food.json
          - examples/food.md
      - <<: *jsonschema2md
        id: jsonschema2md-ms2rescore
        files: examples/ms2rescore.json
        args:
          - --pre-commit
          - examples/ms2rescore.json
          - examples/ms2rescore.md
      - <<: *jsonschema2md
        id: jsonschema2md-vegetables
        files: examples/vegetables.json
        args:
          - --pre-commit
          - examples/vegetables.json
          - examples/vegetables.md
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        exclude: ^(.*/)?poetry\.lock$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.8.1 # npm
          - prettier-plugin-sh@0.12.8 # npm
          - prettier-plugin-toml@0.3.1 # npm
          - '@prettier/plugin-xml@0.12.0' # npm
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
      - id: shellcheck
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: git-check
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.20.0
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
      - id: check-jsonschema
        name: Check GitHub Workflows set timeout-minutes
        files: ^\.github/workflows/[^/]+$
        types:
          - yaml
        args:
          - --builtin-schema
          - github-workflows-require-timeout
  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.5
    hooks:
      - id: ripsecrets
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
      - id: autoflake
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args:
          - --py38-plus
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
